start ../cmdow.exe N1 /cls
start ../cmdow.exe N2 /cls
start ../cmdow.exe N3 /cls
start ../cmdow.exe N4 /cls
start ../cmdow.exe N5 /cls
start ../cmdow.exe N6 /cls
start ../cmdow.exe N7 /cls
start ../cmdow.exe H1 /cls
start ../cmdow.exe H2 /cls
start ../cmdow.exe H3 /cls
start ../cmdow.exe CableCloud /cls
start ../cmdow.exe CCRC1 /cls
start ../cmdow.exe CCRC2 /cls
start ../cmdow.exe CCRC3 /cls
start ../cmdow.exe NCC1 /cls
start ../cmdow.exe NCC2 /cls